[package]
name = "dash-mpd"
version = "0.21.0"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "Download streaming media from a DASH MPD manifest"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-rs"
license = "MIT"
keywords = ["video", "streaming", "MPD", "DASH", "MPEG"]
categories = ["multimedia", "multimedia::video", "parser-implementations"]
publish = true
edition = "2021"

[dependencies]
dash-mpd-core =  { version = "0.1.0", features = ["scte35"] }
base64 = "0.23.1"
byteorder = "1.5.0"
url = "2.5.8"
chrono = { version = "0.4.45", features = ["serde"] }
num-traits = "0.2.19"
iso8601 = "0.6.6"
regex = { version = "1.13.1", default-features = false, features = ["std", "unicode-perl"] }
tracing = { version = "0.1.44", features = ["attributes", "std"] }
data-url = { version = "0.3.2" }
bytes = "1.12.1"
reqwest = { version = "0.13.5", default-features = false, features = ["cookies", "charset", "system-proxy"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "time", "macros", "fs", "io-util"] }
futures-util = "0.3.34"
backon = { version = "1.6.0", features = ["tokio"] }
governor = { version = "0.10.4" }
xot = { version = "0.31.2" }
tempfile = { version = "3.27.0" }
sanitise-file-name = { version = "1.0.0" }
ffprobe = { version = "0.4.0" }
file-format = { version = "0.29.0", features = ["reader"] }
bstr = { version = "1.13.1" }
hex-literal = { version = "1.1.0" }
pssh-box = { version = "0.2.5", features = ["protox"] }
humantime = { version = "2.4.0" }
hxdmp = "0.2.1"
webm-iterable = "0.7.1"
edit-distance = "2.2.2"
mp4-atom = "0.16.1"
xmlparser = "0.13.6"
oxideav-subtitle = { version = "0.1.2", default-features = false }
strip-ansi-escapes = "0.2.1"
dir_spec = { version = "0.5.2", optional = true }
ac-ffmpeg = { version = "0.19.0", optional = true }
xee-xslt-compiler = { version = "0.1.6", optional = true }

[dev-dependencies]
digest-io = "0.1.0"
sha2 = "0.11.0"
hex-literal = "1.1.0"
colored = "3.1.1"
indicatif = "0.18.6"
clap = "4.5.60"
tokio = { version = "1.53.2", features = ["rt-multi-thread", "time", "macros"] }
time = { version = "0.3.55", features = ["macros"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "local-time", "ansi", "tracing-log"] }
quick-xml = { version = "0.42.0", features = ["serialize", "overlapped-lists"] }
proptest = "1.11.0"
http = "1.5.0"
axum = "0.8.9"
axum-auth = "0.8.1"
axum-server = "0.8.0"
reqwest = { version = "0.13.5", default-features = false, features = ["cookies", "json", "blocking"] }
serde_json = "1.0.151"
anyhow = "1.0.104"
roxmltree = "0.21.1"
xmlem = "0.5.0"
jzon = "0.12.5"
mp4 = "0.14.0"
image = "0.25.10"
revelo = "0.5.6"
pretty_assertions = "1.4.1"
approx = "0.5.1"
assert_cmd = "2.2.2"

[features]
default = ["native-tls", "compression", "socks", "http2"]
libav = ["dep:ac-ffmpeg"]
compression = ["reqwest/gzip", "reqwest/brotli", "reqwest/zstd"]
socks = ["reqwest/socks"]
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls"]
hickory-dns = ["reqwest/hickory-dns"]
http2 = ["reqwest/http2"]
# This option currently requires the RUSTFLAGS='--cfg reqwest_unstable' environment variable to be set.
http3 = ["reqwest/http3"]
sandbox = ["dep:landlock", "dep:dir_spec"]
xee-xslt = ["dep:xee-xslt-compiler"]

[target.'cfg(unix)'.dependencies]
xattr = "1.6.1"

[target.'cfg(target_os="linux")'.dependencies]
landlock = { version = "0.4.7", optional = true }
