# Run cargo tests in a FreeBSD VM. This needs to run on one of the GitHub macos runners, because
# they are currently the only ones to support virtualization.
#
# See https://github.com/vmactions/freebsd-vm

on: [push]

name: freebsd

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests in FreeBSD VM
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        sync: rsync
        copyback: false
        mem: 2048
        prepare: |
          pkg install -y curl
          curl https://sh.rustup.rs -sSf --output rustup.sh
          sh rustup.sh -y --profile minimal --default-toolchain stable
          export PATH="${HOME}/.cargo/bin:$PATH"
          echo "~~~~ rustc --version ~~~~"
          rustc --version
          pkg install -y Bento4
          mp4decrypt || true
          pkg install -y ffmpeg
          pkg install -y multimedia/gpac-mp4box
          mp4box -version

        run: |
          export PATH="${HOME}/.cargo/bin:$PATH"
          ls -la
          cargo build
          cargo test
